columns:
  - Vehicle_Model: category
  - Mileage: int
  - Maintenance_History: category
  - Reported_Issues: int
  - Vehicle_Age: int
  - Fuel_Type: category
  - Transmission_Type: category
  - Engine_Size: int
  - Odometer_Reading: int
  - Last_Service_Date: date
  - Warranty_Expiry_Date: date
  - Owner_Type: category
  - Insurance_Premium: int
  - Service_History: int
  - Accident_History: int
  - Fuel_Efficiency: float
  - Tire_Condition: category
  - Brake_Condition: category
  - Battery_Status: category
  - Need_Maintenance: int

numerical_columns:
  - Mileage
  - Reported_Issues
  - Vehicle_Age
  - Engine_Size
  - Odometer_Reading
  - Insurance_Premium
  - Service_History
  - Accident_History
  - Fuel_Efficiency



categorical_columns:
  - Vehicle_Model
  - Maintenance_History
  - Fuel_Type
  - Transmission_Type
  - Last_Service_Date
  - Warranty_Expiry_Date
  - Owner_Type
  - Tire_Condition
  - Brake_Condition
  - Battery_Status

drop_columns: []

target_column: Need_Maintenance

date_columns:
  - Last_Service_Date
  - Warranty_Expiry_Date


mm_columns: []

